apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: catalog-metrics
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dockerhub-metrics
            image: guangbo/catalog-metrics:dev
            command: ["catalog-metrics",  "hub"]
            env:
            - name: INFLUX_SERVER
              value: "10.43.97.22"
            - name: INFLUX_PORT
              value: "8086"
          restartPolicy: OnFailure
